mybatis:
  typeAliasesPackage: com.chuhe.mall.model
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.128:3306/chuhe?useUnicode=true&characterEncoding=utf8
    username: chuhe
    password: chuhe2018
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource